dataset: fashion

analysis:
  num_samples: 1000
  fixed_indices: [0, 1, 2, 3, 4]
  noise_sigmas: [0.0, 0.05, 0.1, 0.2, 0.3]
  interp_steps: 9
  interp_noise_sigma: 0.02
  tsne_perplexity: 30
  batch_size: 256
  num_workers: 4
  seed: 42
  save_pdf: true
  include_optical_intensity: false
  optical_vis:
    use_log1p: true
    cmap: magma
  electronic_vis:
    topk_channels: 4

checkpoints:
  electronic: ./outputs/fashionmnist_vae_small_z100/checkpoints/best.pt
  opticals:
    # - name: opt_default
    #   path: ./outputs/map_opt_fashionmnist/checkpoints/best.pt
    - name: opt_iid_l20_NoPool
      path: ./outputs/map_opt_fashionmnist_iid_l_20_NoPool/checkpoints/best.pt
    - name: opt_iid_l20
      path: ./outputs/map_opt_fashionmnist_iid_l_20/checkpoints/best.pt
    - name: opt_corr20_l5
      path: ./outputs/map_opt_fashionmnist_corr_20_l_5/checkpoints/best.pt